#load packages

library(optparse)
library(randomForest)
library(data.table)
library(RSpectra)
library(mhsmm)
library(parallel)
library(stringr)
library(doMC)
library(foreach)
library(MASS)
library(Rcpp)
library(bigmemory)
library(biganalytics)
library(bigpca)
library(irlba)
library(bigalgebra)
library(Matrix)
library(SparseM)